                     ;fIND THE LARGEST NUMBER IN ARRAY 
MOV SI,1000H
MOV DI,1200H
MOV CL,[SI] ;1ST ELEMENT IN ARRAY IS COUNT
INC SI
MOV AL,[SI] ;AL HAS 1ST NUM
DEC CL     
LOOP1: INC SI
MOV BL,[SI] ;BL HAS 2ND NUM
CMP AL,BL
JNC LABLE2   ;AL HAS GREATER NUM
MOV AL,BL   ; IF CARRY THEN LARGER NUMBER IS MOVED TO AL
LABLE2: DEC CL  ;COUNT
JNZ LOOP1
MOV [DI],AL ;RESULT IN [DI]
HLT