;MATRIX MULTIPLICATION
MOV SI,1301H ;SET SI AS POINTER FOR FIRST MATRIX
MOV DI,1401H ;SET DI AS POINTER FOR SECOND MATRIX
MOV BP,1501H ;SET BP AS POINTER FOR PRODUCT MATRIX 
MOV CL,03H   ;SET CL A COUNT FOR ELEMENTS IN ROW
MOV CH,03H   ;SET CH A COUNT FOR ELEMENTS IN COLUMN
MOV DH,CH

REPEAT3:
MOV BL,DH

REPEAT2:
MOV DL,00H
MOV CH,DH
 
REPEAT1:
MOV AL,[SI]
MUL [DI]
ADD DL,AL
INC SI 
ADD DI,03
DEC CH 
JNZ REPEAT1
MOV [BP],DL
INC BP
SUB SI,03H
SUB DI,09H
INC DI
DEC BL
JNZ REPEAT2
ADD SI,03H
MOV DI,1401H
DEC CL
JNZ REPEAT3
HLT
